# Project: Project2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = "../Aula\ 2/main.o"
LINKOBJ  = "../Aula 2/main.o"
LIBS     = -L"C:/devSources/Dev-Cpp/MinGW64/lib" -L"C:/devSources/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/devSources/Dev-Cpp/MinGW64/include" -I"C:/devSources/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/devSources/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/devSources/Dev-Cpp/MinGW64/include" -I"C:/devSources/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/devSources/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/devSources/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "aula 2.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

"../Aula\ 2/main.o": ../Aula\ 2/main.c
	$(CC) -c "../Aula 2/main.c" -o "../Aula 2/main.o" $(CFLAGS)
